spring.application.name=salmon
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/salmon_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.config.import=optional:file:./.env[.properties]
scrapingbee.api.key=${SCRAPINGBEE_API_KEY_ONE}
bot.token=7958632055:AAH14LN8GJOwH9fxydun19zaHMc_Gz9O4b0
bot.username=SalmonApplicationBot